### PR TITLE
Update book.rust-embedded.org to gh cname record

### PR DESCRIPTION
**Pull request by ryankurte**
Fixes issue #2

### CODE REVIEW

**Comment by ryankurte** [comment]
boop @nastevens (I haven't got permissions to assign ya)

**Comment by nastevens** [comment]
@ryankurte Really sorry I didn't see this sooner... I did not have PR alerts on this repo enabled apparently. I appreciate the boop :-)

One thing - the `book.rust-embedded.org` A record is also pointed at one of James' servers. Should that also be updated to a CNAME?

**Comment by ryankurte** [comment]
No worries! And whoops, yeah you're totally right / I meant to remove that. Changed now!

I wonder whether we can convince a bot to render out the tf changes that'd be applied by a pr against the state in the repo, might look into that at some point.

**Comment by nastevens** [comment]
Applied and merged - thank you!

**Comment by nastevens** [comment]
Oh, and there's a really cool tool called Atlantis that will do exactly what you're talking about and show what the results of the `terraform plan` would be in the PR: https://www.runatlantis.io/. I'd really like to get that set up on this repo.

**Comment by ryankurte** [comment]
Thanks, and that's interesting! I uhh, am not sure it's useful for public repos, looks like it's missing auth. And it's a bit weird to apply things from PR comments instead of on merge?

**Comment by nastevens** [comment]
Ew, I had assumed there'd be a way to disable the apply from PR but I didn't find anything from a perusal of the docs... That's what I get for assuming. Re-reading my statement, I definitely made it sound like "we should 100% use this tool" when really it was "I've heard of this tool and it seemed like it might be useful, I'd like to investigate".

**Comment by ryankurte** [comment]
Yeah I figured. I have some ideas from some ops friends we can play with once this repo is transferred to the rust-embedded org and I have permissions to edit settings etc.

**Pull request merged**
